# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Setup
title:            Ember Simple Auth
tagline:          'Guides'
description:      'A set of getting started guides for working with <a href="https://ember-simple-auth.com" target="_blank">Ember Simple Auth</a>.'
url:              http://rtablada.github.io/simple-auth-guide/
baseurl:          /

author:
  name:           'Ryan Tablada'
  url:            http://twitter.com/ryantablada

github:
  repo:           https://github.com/rtablada/simple-auth-guide
